### PR TITLE
Update contentmanager.cpp

### PR DESCRIPTION
**Pull request by steinwedel**
added file:// URL for Json template

With this extension Json template files can be paced on local files system of AP and then accessed by JSON Template. Example: file:///test.json

### CODE REVIEW

**Comment by nlimper** [comment]
Thanks for the PR.
But, this is kind of duplicate: there is already code to handle a tempate file, in https://github.com/jjwbruijn/OpenEPaperLink/blob/master/ESP32_AP-Flasher/src/contentmanager.cpp#L331 . That's one is used if you upload a json file. Just some hours ago, I added the filename as a parameter in the content card. If you replace the latest /www/content_cards.json, you can enter the filename in the config screen.

**Comment by steinwedel** [comment]
Hi Nic, this is somehow duplicate. The idea behind is, that in future you can retrieve info from several different sources. E.G. also fonts from external servers. Therefore it makes sense to have one syntax in all situations. For fonts the syntax may be future like {"text": [215,5,"70","http://www.fonts.org/thefont.ttf",1]}, or {"text": [215,5,"70","file:///fonts/thefont.ttf",1]}. With your current scheme this does not work. Als vars could be loaded by this way from local or extern. Perhaps it is worth to think about this again.

**Comment by steinwedel** [comment]
There is some more duplicate code. You have e.g. the upload for json files. You can upload files via "edit contentFS". The "edit contentFS" is more general and can be used for several situations e.g. upload images and fonts. If you enhance the jsontemplate to put images etc. this would me more flexible. The current way via an extra menu point would be then obsolete. With this syntax you could handle internal and external images with one jsontemplate syntax.

**Comment by nlimper** [comment]
Ah, I understand now!
I will think about it. In any way, "http://www.fonts.org/thefont.ttf" is never going to work (except when the file is first downloaded to the filesystem) because the extensive file seeking back and forth when rendering the truetype glyphs.

**Pull request closed without merging**
